name: "Claude Auto Review"
description: "Automated code review using Claude AI with configurable project context"
author: "WalletConnect"

inputs:
  anthropic_api_key:
    description: "Anthropic API key for Claude access"
    required: true
  model:
    description: "Claude model to use for reviews"
    required: false
    default: "claude-sonnet-4-5-20250929"
  timeout_minutes:
    description: "DEPRECATED: Accepted but ignored by v1 (no effect). Use job-level timeout-minutes instead."
    required: false
  custom_prompt:
    description: "Complete custom prompt override. If provided, all other prompt-related inputs are ignored."
    required: false
  project_context:
    description: "Additional project-specific context to help Claude understand your codebase"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up review prompt
      shell: bash
      run: |
        # Create prompt header with context
        PROMPT_HEADER="REPO: ${{ github.repository }}
        PR NUMBER: ${{ github.event.pull_request.number }}

        "

        if [[ -n "${{ inputs.custom_prompt }}" ]]; then
          # Use custom prompt directly with header
          PROMPT="${PROMPT_HEADER}${{ inputs.custom_prompt }}"
        else
          # Build dynamic prompt based on inputs
          PROMPT="${PROMPT_HEADER}Review this pull request with focus on code quality, security, and best practices.

        **IMPORTANT: For PR synchronize events (subsequent pushes), be incremental:**
        1. First, examine all existing review comments in this PR thread for context
        2. For each issue mentioned in previous comments (from any tool), **validate if it still exists** in the current code state
        3. **CRITICAL: Only report previously mentioned issues if you can confirm they still exist** by examining the actual current code
        4. Clearly note when previously flagged issues have been resolved since the last review
        5. Flag any genuinely **new** issues found in the latest commits
        6. When referencing issues originally identified by other tools (GitHub Copilot, Cursor, etc.), explicitly validate their current relevance and state \"Confirmed still present\" or \"Resolved since previous review\"

        **For initial PR reviews or if no previous comments exist, provide a full review.**

        Focus on:
        - **Code quality and best practices** for the technologies used in this project
        - **Potential bugs or issues** especially in critical code paths and async operations
        - **Performance considerations** for both frontend and backend code
        - **Security implications** particularly for authentication, API endpoints, and data handling
        - **Test coverage** and quality of test implementations
        - **Documentation updates** if needed for significant changes
        - **Type safety** and proper usage of type systems
        - **Error handling** and edge cases
        - **Code maintainability** and readability

        **EXTERNAL DOMAIN URL DETECTION:**
        Scan all changed files for URLs matching the pattern 'https?://(?:www\.)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})'. If any URLs are found pointing to domains other than the approved company domains (reown.com, walletconnect.com, walletconnect.org), report them using this exact format:

        🔒 **External Domain URL Detected** (Non-blocking)
        **URL:** [detected_url]
        **File:** [file_path:line_number]

        This change introduces URLs pointing to external domains. Please verify that these external dependencies are intentional and review for potential security, privacy, or compliance implications. Approved company domains are: reown.com, walletconnect.com, walletconnect.org"


          # Add project context
          if [[ -n "${{ inputs.project_context }}" ]]; then
            PROMPT="$PROMPT

        **Project-specific context:**
        ${{ inputs.project_context }}"
          fi

          # Add response format guidelines
          PROMPT="$PROMPT

        **Response Format:**
        - For incremental reviews: Start with \"🔄 Incremental Review:\" and focus only on changes since last review
        - For full reviews: Be concise - only mention problems that need fixing
        - If no new issues found: \"✅ No new issues found in latest commits\"
        - Do not praise or describe what is working well

        Provide constructive feedback with specific suggestions for improvement.
        Use inline comments to highlight specific areas of concern.
        Consider the impact on the overall system architecture and user experience."
        fi

        # Set environment variable for the next step
        echo "REVIEW_PROMPT<<EOF" >> $GITHUB_ENV
        echo "$PROMPT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Check timeout_minutes deprecation
      shell: bash
      run: |
        if [[ -n "${{ inputs.timeout_minutes }}" ]]; then
          echo "::warning::The 'timeout_minutes' input is deprecated and has no effect in claude-code-action@v1. Please use job-level 'timeout-minutes' instead. See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes"
        fi

    - name: Automatic PR Review
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        prompt: ${{ env.REVIEW_PROMPT }}
        track_progress: true
        claude_args: --model ${{ inputs.model }}
        allowed_bots: devin-ai-integration[bot]
