name: "Get latest release version"
description: "Gets the version number of the latest release"

outputs:
  version:
    description: "The version number of the latest release"
    value: ${{ steps.clean_version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Get latest release
      id: latest_release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        excludes: draft

    - name: Get release value
      id: get_value
      uses: actions/github-script@v6
      env:
        LATEST_TAG: ${{ steps.latest_release.outputs.release }}
      with:
        result-encoding: string
        script: |
          if (context.eventName == "release") {
            return context.payload.release.tag_name
          } else {
            return process.env.LATEST_TAG
          }

    - name: Clean version
      id: clean_version
      shell: bash
      run: |
        version=$(echo "${{ steps.get_value.outputs.result }}" | sed 's/v//g')
        echo "version=$version" >> $GITHUB_OUTPUT
